name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: verify and build
      id: verify-and-build
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: verify and build
        setup-command: mvn clean install
        command: mvn verify
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        VERIFY-AND-BUILD_RESULTS: "${{steps.verify-and-build.outputs.result}}"
      with:
        runners: verify-and-build
